### ISSUE TITLE
404s galore!

### ISSUE THREAD

**Issue by garrett** [cthiel/cardboard#51]
There's something wrong with the Sprocket asset pipeline.

The needed files are loading, but it's trying to load them from incorrect places first.

**Comment by cthiel** [comment]
Only in development, I guess?

**Comment by garrett** [comment]
I guess. I don't know how I'd check production mode.

**Comment by cthiel** [comment]
Fixed with commit 5be6d0a647962f720b3aae98b458dcd4accfe760

**Comment by garrett** [comment]
Are you sure?

It looks like things are broken now, as in 'jQuery not defined'

Also, I still get a 404 for a stylesheet, too.

**Comment by cthiel** [comment]
Now it's really fixed with 8d389fb89e0720881b90e55562d0d8854a8a9dc0

**Comment by garrett** [comment]
In development mode, I still get 404s for:
- http://localhost:3000/assets/application-cc3be92f2d905f25307d3fd36502e879.css?body=1
- http://localhost:3000/assets/lib-28a3b63f99082f45f9bbc5bcd62792d5.js?body=1

Both say "Routing Error" if I look at each URL directly.

**Comment by cthiel** [comment]
Also fixed now -- the files were missing "require_self"...

**Comment by garrett** [comment]
`require_self` sounds so odd. I'm (so far) not a fan of Sprockets.

**Comment by garrett** [comment]
I still have the problem with application*.css

**Comment by cthiel** [comment]
I don't, now that I have added a newline to the file.

**Comment by garrett** [comment]
A _new_ line? what's the matter with the old lines? (:

(Seriously though, this seems to fix the last 404... _for now_.)
